-- Punchlines retravaillées (série 2) : met à jour les exhortations déjà
-- intégrées en base (positions 105 à 204). Sans effet sur les autres.
update public.devotions as d
set punchline = v.punchline, updated_at = now()
from (values
  (105, 'Une maison ne sert pas Dieu par hasard, mais par décision.'),
  (106, 'Dans la maison de Dieu, aucun enfant n''est orphelin.'),
  (107, 'Le juste tombe. Mais il se relève encore.'),
  (108, 'Le courage n''attend pas la fin de la peur. Il avance avec Dieu.'),
  (109, 'Ton don n''est pas un projecteur. C''est un outil pour servir.'),
  (110, 'Dans le corps de Christ, personne n''est inutile. Personne n''est seul.'),
  (111, 'Ton corps n''est pas une vitrine. C''est un temple.'),
  (112, 'Tu peux tout faire pour Jésus et ne plus aimer Jésus.'),
  (113, 'Même oublié des hommes, tu restes gravé dans les mains de Dieu.'),
  (114, 'Jésus ne t''attend pas au sommet. Il te rejoint là où tu es.'),
  (115, 'Quand Dieu est le troisième fil, le couple résiste.'),
  (116, 'Ceux qui t''abandonnent n''ont pas le dernier mot : Dieu te recueille.'),
  (117, 'Jésus ne te demande pas si tu as échoué, mais si tu l''aimes.'),
  (118, 'Ce qui te semble tard n''est jamais en retard pour Dieu.'),
  (119, 'Dans le Royaume, le plus grand n''est pas servi. Il sert.'),
  (120, 'Partagé, le fardeau ne disparaît pas. La solitude, si.'),
  (121, 'Une pensée peut passer. Ne la laisse pas régner.'),
  (122, 'La foi ignore parfois où elle va. Elle sait qui l''appelle.'),
  (123, 'Dieu ne te tolère pas. Il se réjouit de toi.'),
  (124, 'Tant que tu peux regarder Jésus, il n''est pas trop tard.'),
  (125, 'Tes enfants entendent tes paroles. Ils reproduisent ta vie.'),
  (126, 'Dieu ne condamne pas tes larmes. Il promet sa consolation.'),
  (127, 'Ta chute n''est pas ta fin. Dieu te relèvera.'),
  (128, 'Tu ne peux pas imposer la paix. Tu peux refuser d''alimenter la guerre.'),
  (129, 'Qui méprise les petites fidélités n''est pas prêt pour les grandes.'),
  (130, 'Un encouragement aujourd''hui peut empêcher une chute demain.'),
  (131, 'Ta compréhension a des limites. Ta confiance en Dieu n''en a pas besoin.'),
  (132, 'Dieu n''attend pas tes capacités. Il demande ta disponibilité.'),
  (133, 'Quand ses voies te dépassent, appuie-toi sur son cœur.'),
  (134, 'L''amour de Dieu ne s''est pas contenté de mots : il a donné son Fils.'),
  (135, 'Honorer n''est pas tout approuver. C''est refuser de mépriser.'),
  (136, 'Ton corps s''use. En Dieu, ton être intérieur se renouvelle.'),
  (137, 'Tu n''avanceras pas tant que ton regard habitera hier.'),
  (138, 'Le contentement ne vient pas d''avoir tout, mais d''avoir Christ.'),
  (139, 'Fais tes plans. Laisse Dieu tracer tes pas.'),
  (140, 'Une Église forte ne vit pas d''événements, mais de fidélité.'),
  (141, 'L''obéissance n''achète pas l''amour de Dieu. Elle y répond.'),
  (142, 'Une petite foi en un grand Dieu peut déplacer des montagnes.'),
  (143, 'La consolation de Dieu ne s''arrête pas à toi. Elle passe par toi.'),
  (144, 'Tu peux tout perdre, sauf l''amour de Dieu.'),
  (145, 'L''amour se célèbre aux beaux jours. Il se prouve dans l''épreuve.'),
  (146, 'Dieu ne jette pas les cœurs brisés. Il les panse.'),
  (147, 'Le Potier ne jette pas le vase raté. Il le refait.'),
  (148, 'L''amertume ne blesse pas ton offenseur. Elle prolonge ta blessure.'),
  (149, 'Ne compte pas seulement tes années. Fais compter tes jours.'),
  (150, 'Toute tentation a une issue. À toi de la prendre.'),
  (151, 'Jeûner, ce n''est pas seulement vider l''assiette. C''est creuser la faim de Dieu.'),
  (152, 'À « Qui suis-je ? », Dieu répond : « Je serai avec toi. »'),
  (153, 'Parfois, combattre, c''est s''arrêter et laisser Dieu agir.'),
  (154, 'Tes larmes ont une fin. La promesse de Dieu n''en a pas.'),
  (155, 'Les vrais amis ne brillent pas dans la fête. Ils restent dans l''épreuve.'),
  (156, 'Jésus connaît la fin. Pourtant, il pleure avec toi.'),
  (157, 'Dieu ne réécrit pas ton passé. Il restaure ce qu''il t''a volé.'),
  (158, 'Craindre le regard des hommes, c''est leur donner la place de Dieu.'),
  (159, 'Le repos n''est pas le prix du travail fini. C''est la grâce pour continuer.'),
  (160, 'La pureté n''est pas une prison d''interdits. C''est un chemin éclairé par la Parole.'),
  (161, 'Dieu ne t''envoie pas témoigner seul. Il te revêt de sa puissance.'),
  (162, 'Dieu ne t''appelle pas selon tes limites, mais selon son dessein.'),
  (163, 'Avant de craindre demain, rappelle-toi jusqu''où Dieu t''a porté.'),
  (164, 'La terre n''est pas ta destination. Jésus te prépare une place.'),
  (165, 'Ceux que tu fréquentes façonnent celui que tu deviens.'),
  (166, 'Quand ton cœur vole en éclats, Dieu se tient au plus près.'),
  (167, 'La comparaison vole ta joie. L''obéissance la restaure.'),
  (168, 'Même tremblante, la foi qui crie vers Jésus est entendue.'),
  (169, 'Une main fermée ne sème rien. Elle ne récolte rien.'),
  (170, 'Face à certaines tentations, fuir n''est pas lâche. C''est vaincre.'),
  (171, 'Dieu ne cherche pas de belles chansons, mais de vrais adorateurs.'),
  (172, 'Tout change. Jésus reste.'),
  (173, 'Jésus n''est pas un spectateur lointain. Il est le Berger qui donne sa vie.'),
  (174, 'Ce que tu vois passe. Ce que Dieu prépare demeure.'),
  (175, 'Dieu préfère une réconciliation sincère à une offrande religieuse.'),
  (176, 'Ce qu''on a voulu pour ton mal, Dieu peut le tourner en bien.'),
  (177, 'La colère peut frapper. Ne lui offre pas un lit.'),
  (178, 'L''orgueil te fait monter vite — pour mieux précipiter ta chute.'),
  (179, 'L''excellence n''est pas l''orgueil. C''est honorer Dieu avec ce qu''il confie.'),
  (180, 'Tu ne résistes pas au diable par la force, mais par la soumission à Dieu.'),
  (181, 'Dieu parle encore. Mais nous parlons trop pour l''entendre.'),
  (182, 'Invisible aux hommes. Jamais invisible à Dieu.'),
  (183, 'Jésus ne montre pas le chemin. Il est le chemin.'),
  (184, 'Tes pieds sont sur terre. Ta citoyenneté est au ciel.'),
  (185, 'Aimer comme Christ, ce n''est pas réclamer. C''est se donner.'),
  (186, 'La honte t''a couvert. Dieu veut te revêtir d''honneur.'),
  (187, 'Tes mots bâtissent ou détruisent. Jamais neutres.'),
  (188, 'Quand Dieu ne t''abandonne pas, tu n''as pas besoin de tout posséder.'),
  (189, 'Une braise isolée s''éteint. Ensemble, le feu demeure.'),
  (190, 'Ce que tu contemples longtemps finit par habiter ton cœur.'),
  (191, 'Parfois, l''acte le plus spirituel est de t''arrêter.'),
  (192, 'Ton impossible n''est jamais trop difficile pour Dieu.'),
  (193, 'Ce qui ne peut combler ton cœur te laissera toujours assoiffé.'),
  (194, 'Le Tout-Puissant s''est fait enfant pour se rendre proche.'),
  (195, 'Tu ne choisis pas la tempête. Mais tu peux refuser d''y ajouter du vent.'),
  (196, 'Quand tu es à bout, Dieu sait commencer par le repos.'),
  (197, 'La grâce d''aujourd''hui ne t''a pas été donnée pour porter demain.'),
  (198, 'Fait pour Dieu, ton travail devient adoration.'),
  (199, 'Là où les frères choisissent l''unité, Dieu ordonne la bénédiction.'),
  (200, 'Ce que tu tolères en petit peut ravager en grand.'),
  (201, 'Dieu ne cherche pas ta course pour lui, mais ta marche avec lui.'),
  (202, 'Pour le monde, un numéro. Pour Dieu, un nom.'),
  (203, 'Jésus ne force pas la porte. Il frappe. À toi d''ouvrir.'),
  (204, 'Le tombeau vide prouve que la mort n''a pas le dernier mot.')
) as v(position, punchline)
where d.position = v.position;
